[supabase]
url = "https://oqvnsvozxrwahzywajtp.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdm5zdm96eHJ3YWh6eXdhanRwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDQzMTE0NiwiZXhwIjoyMDcwMDA3MTQ2fQ.FrapERUTUXNwmjk6oPUNZlQQ50-Xfu3nuICpJroE3mA"

[email]
address = "canchacolina148@gmail.com"
password = "likp wpvm wdze ntmm "